### ISSUE TITLE
When component is generated it should be in a separate folder

### ISSUE THREAD

**Issue by farisT** [liftr-framework/cli#13]
As title says, this should link with https://github.com/farisT/liftr/issues/12 so that all the components have their own folder in their respective root folders. There can also be a flag to create within the component root folder itself instead of creating a folder.

**Comment by theghostyced** [comment]
Hi, @farisT Am looking to pick this up but I don't quite understand the full definition of a `component`. At first, I thought you were referring to a controller but then realized you already had a script for that.

So before I pick it up, can you shed a little light on it 💡?

**Comment by farisT** [comment]
Hi @theghostyced, glad to see you are interested in picking this up. Just to clarify, the definition of a `component` is  a `route`, `middleware` or `controller`. At the moment these are created within their specific folders with the titles "Routes", "Middleware", "Controllers".
The idea of this issue was to be able to have the choice to create one of these components within that folder but have their own sub-directory (with possibly a flag)

So when I create a middleware file with `liftr -m MyMiddleware` it should be created in the "Middleware" folder but be in its own sub-directory.

<img width="322" alt="Schermafbeelding 2019-06-30 om 14 48 14" src="https://user-images.githubusercontent.com/33259789/60396793-2b6b9e80-9b46-11e9-8e91-a53969cff5c6.png">

Maybe if you create a  `--flat` flag it defaults to the current behaviour (just create in the middleware folder, no sub-directory)

So the previous command would look like `liftr -m MyMiddleware --flat`.

Hope this is enough information for you to work with!

**Comment by farisT** [comment]
This was completed in https://github.com/farisT/liftr-cli/releases/tag/v2
Closing issue
