### ISSUE TITLE
Can't start `npm start` because of missing joi package in core

### ISSUE THREAD

**Issue by devbyray** [liftr-framework/cli#17]
@farisT I'm getting this error, so I can't run the server :-( 

<img width="703" alt="Screenshot 2020-02-26 at 20 38 19" src="https://user-images.githubusercontent.com/6241164/75380961-3397fb80-58d8-11ea-8e4e-e05d92b2a64f.png">

**Comment by devbyray** [comment]
It looks like `joi` is deprecated! https://www.npmjs.com/package/joi

**Comment by farisT** [comment]
Resolved with version 1.1.0 of @liftr/core. Please update your version :)
