### ISSUE TITLE
Can't create project since '-s' is unknown option

### ISSUE THREAD

**Issue by Airdevelopments** [liftr-framework/cli#21]
After installing the package globally using
`npm i -g @liftr/cli`
I tried creating a project, but running
`liftr -s test`
causes the following error
`error: unknown option '-s'`

Am I doing something wrong / do I require some peer dependencies or ist the latest release bugged?

Liftr-cli version: 3.0.0
NodeJS version: 12.2.0
NPM version: 6.10.2
OS: Win10 Pro 64bit

Edit: Same goes for '--setup' option

**Comment by farisT** [comment]
Hi @Airdevelopments,  in the newest version of the @liftr/cli (v3) to setup a project you run:

`liftr create setup`

All the components can also be built by using `liftr create <component-name>` 
I noticed that the README still has the old `liftr -s <project-name>` I will update that right away :).

**Comment by Airdevelopments** [comment]
Thank you for the fast response. Much appreciated!
